### ISSUE TITLE
Front Page

### ISSUE THREAD

**Issue by rhcarlosweb** [rhcarlosweb/EDD-Theme#2]
First version wireframe mobile
![front-page-mobile](https://cloud.githubusercontent.com/assets/4534115/20457116/8fd11b4a-ae6b-11e6-939d-0076d2577aff.jpg)

**Comment by rhcarlos** [comment]
Initial header and featured item (maybe a slider feature)

![front-page](https://cloud.githubusercontent.com/assets/4534115/20458826/d2e04728-ae96-11e6-82b1-06d392094082.jpg)

**Comment by rhcarlosweb** [comment]
One more update for front page
![front-page](https://cloud.githubusercontent.com/assets/4534115/20460635/75c05882-aed0-11e6-8bb9-3bdd100abb10.jpg)

**Comment by rhcarlosweb** [comment]
- Changed gradient buttons
- Changed radius buttons
- Changed positions itens menu
- Hide Search and changed to button

![front-page](https://cloud.githubusercontent.com/assets/4534115/20460921/13f31a78-aed9-11e6-96bf-bd6f8b69f8b5.jpg)
